# Exported from:        http://centos1:5516/
# Release version:      10.2.0-SNAPSHOT
# Date created:         Wed May 26 20:59:02 EDT 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: SDLM
spec:
- name: GitRepo
  type: git.Repository
  url: https://github.com/pdgibbons/SDLM
  username: pgibbons
  password: !value "git_Repository_GitRepo_password"
- name: gitrepo2
  type: git.Repository
  url: https://github.com/pdgibbons/ACME
  username: pgibbons
  password: !value "git_Repository_gitrepo2_password"
